/// Represents a dynamic activity recommendation generated by NIMO's Recommendation Engine.
class RecommendationModel {
  final String recommendationId;
  final String childId;
  final String activityId;
  final String skill;
  final int difficulty;
  final double priority;
  final String reason;
  final String generatedAt;

  const RecommendationModel({
    required this.recommendationId,
    required this.childId,
    required this.activityId,
    required this.skill,
    this.difficulty = 1,
    this.priority = 0.5,
    required this.reason,
    required this.generatedAt,
  });

  factory RecommendationModel.fromJson(Map<String, dynamic> json) {
    return RecommendationModel(
      recommendationId: json['recommendationId'] as String? ?? 'REC_LOCAL',
      childId: json['childId'] as String? ?? 'A001',
      activityId: json['activityId'] as String? ?? 'netaji_q01',
      skill: json['skill'] as String? ?? 'sequencing',
      difficulty: json['difficulty'] as int? ?? 1,
      priority: (json['priority'] as num?)?.toDouble() ?? 0.5,
      reason: json['reason'] as String? ?? 'Recommended based on learning priorities.',
      generatedAt: json['generatedAt'] as String? ?? DateTime.now().toIso8601String(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'recommendationId': recommendationId,
      'childId': childId,
      'activityId': activityId,
      'skill': skill,
      'difficulty': difficulty,
      'priority': priority,
      'reason': reason,
      'generatedAt': generatedAt,
    };
  }

  @override
  String toString() {
    return 'RecommendationModel(activityId: $activityId, skill: $skill, priority: $priority, reason: $reason)';
  }
}
